[project]
name = "menero-new"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "alembic>=1.16.2",
    "asyncpg>=0.30.0",
    "disnake>=2.10.1",
    "pydantic-settings>=2.10.1",
    "sqlalchemy>=2.0.41",
]
