services:
  db:
    container_name: ${POSTGRES_HOST}
    image: postgres:16.2-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: ${POSTGRES_TZ}
    ports:
      - ${POSTGRES_PORT}:5432
    restart: unless-stopped
    volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        - ../../storage:/var/lib/postgresql/data

  redis:
    container_name: ${REDIS_HOST}
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - ${REDIS_PORT}:6379

  rabbitmq:
    container_name: ${RABBITMQ_HOST}
    image: rabbitmq:3
    ports:
      - ${RABBITMQ_PORT}:5672
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_VHOST}
    restart: unless-stopped
    volumes:
      - ../../rabbitmq_data:/var/lib/rabbitmq

  auth:
    build:
      context: ..
    env_file: ../../.env
    environment:
      - UV_PROJECT_ENVIRONMENT=/usr/local/menero-new
    depends_on:
      - db
      - redis
      - rabbitmq
    volumes:
      - ../..:/opt/menero-new

networks:
  default:
    driver: bridge
